# Generated by Django 4.2.17 on 2024-12-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_system', '0002_tablebooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='time',
            field=models.CharField(choices=[('09:00', '9:00 AM')], default='9:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
