# Generated by Django 4.2.17 on 2024-12-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_alter_tablebooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='time',
            field=models.CharField(choices=[('09:00', '9:00 AM'), ('11:00', '11:00 AM')], max_length=5),
        ),
    ]
