# Generated by Django 4.2.17 on 2024-12-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0005_alter_tablebooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='time',
            field=models.CharField(choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '13:00 PM'), ('14:00', '14:00 PM'), ('15:00', '15:00 PM'), ('16:00', '16:00 PM'), ('17:00', '17:00 PM'), ('18:00', '18:00 PM'), ('19:00', '19:00 PM'), ('20:00', '20:00 PM'), ('21:00', '21:00 PM')], max_length=5),
        ),
    ]
