# Generated by Django 4.2.17 on 2024-12-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0007_tablebooking_table_number_alter_tablebooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='table_number',
        ),
    ]
