# Generated by Django 4.2.17 on 2024-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0008_remove_tablebooking_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='time',
            field=models.CharField(choices=[('12:00', '12:00 PM'), ('13:00', '13:00 PM'), ('14:00', '14:00 PM'), ('15:00', '15:00 PM'), ('16:00', '16:00 PM'), ('17:00', '17:00 PM'), ('18:00', '18:00 PM'), ('19:00', '19:00 PM'), ('20:00', '20:00 PM')], max_length=5),
        ),
    ]
