# Generated by Django 4.2.17 on 2025-01-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0009_tablebooking_email_tablebooking_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='tables',
            field=models.ManyToManyField(to='booking_system.table'),
        ),
    ]
